server:
  port: 8081
  session-timeout: 30
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#    url: jdbc:mysql://10.216.250.71:3306/hateno_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.2.34:3306/hateno_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true