server:
  port: 8081
  session-timeout: 30
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=true&verifyServerCertificate=true&requireSSL=true&serverSslCert=/path/to/mysql/ca-cert.pem
    username: 3TDq1FDDWkDEMuA.root
    password: 7Auj9unc3rsBEAwQ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true